services:
  backend:
    container_name: backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
    networks:
      - user_auth

  postgres:
    image: postgres:17.2-alpine3.21
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-h",
          "localhost",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - user_auth

  caddy:
    image: caddy:2.8.4-alpine
    container_name: caddy
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    networks:
      - user_auth

volumes:
  postgres:
  caddy_data:
  caddy_config:

networks:
  user_auth:
    driver: bridge
